-- MySQL Script generated by MySQL Workbench
-- Fri Feb  9 10:02:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_train_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_train_db` ;

-- -----------------------------------------------------
-- Schema test_train_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_train_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `test_train_db` ;

-- -----------------------------------------------------
-- Table `test_train_db`.`blooms_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`blooms_tax` (
  `blooms_id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `verbs` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`blooms_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`topics` (
  `topic_id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `facility` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`topic_id`, `subject_id`),
  INDEX `topics_fk_subjects_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `topics_fk_subjects`
    FOREIGN KEY (`subject_id`)
    REFERENCES `test_train_db`.`subjects` (`subject_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`learning_objectives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`learning_objectives` (
  `obj_id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `blooms_id` INT NOT NULL,
  `is_applicant` TINYINT(1) NOT NULL,
  `is_apprentice` TINYINT(1) NOT NULL,
  `is_journeyman` TINYINT(1) NOT NULL,
  `is_senior` TINYINT(1) NOT NULL,
  `is_chief` TINYINT(1) NOT NULL,
  `is_coordinator` TINYINT(1) NOT NULL,
  `tags/metadata` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`obj_id`, `topic_id`),
  INDEX `learningobjs_fk_topics_idx` (`topic_id` ASC) VISIBLE,
  INDEX `learningobjs_fk_blooms_idx` (`blooms_id` ASC) VISIBLE,
  CONSTRAINT `learningobjs_fk_blooms`
    FOREIGN KEY (`blooms_id`)
    REFERENCES `test_train_db`.`blooms_tax` (`blooms_id`),
  CONSTRAINT `learningobjs_fk_topics`
    FOREIGN KEY (`topic_id`)
    REFERENCES `test_train_db`.`topics` (`topic_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`subject_references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`subject_references` (
  `reference_id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` INT NOT NULL,
  `reference_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`reference_id`, `subject_id`),
  INDEX `subrefs_fk_subjects` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `subrefs_fk_subjects`
    FOREIGN KEY (`subject_id`)
    REFERENCES `test_train_db`.`subjects` (`subject_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`topic_references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`topic_references` (
  `topic_reference_id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  `reference_id` INT NOT NULL,
  PRIMARY KEY (`topic_reference_id`, `topic_id`),
  INDEX `toprefs_fk_subrefs_idx` (`reference_id` ASC) VISIBLE,
  INDEX `toprefs_fk_topics_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `toprefs_fk_subrefs`
    FOREIGN KEY (`reference_id`)
    REFERENCES `test_train_db`.`subject_references` (`reference_id`),
  CONSTRAINT `toprefs_fk_topics`
    FOREIGN KEY (`topic_id`)
    REFERENCES `test_train_db`.`topics` (`topic_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`objective_references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`objective_references` (
  `objective_reference_id` INT NOT NULL AUTO_INCREMENT,
  `obj_id` INT NOT NULL,
  `topic_reference_id` INT NOT NULL,
  `page/section` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`objective_reference_id`, `obj_id`),
  INDEX `objrefs_fk_topicrefs_idx` (`topic_reference_id` ASC) VISIBLE,
  INDEX `objrefs_fk_learningobjs_idx` (`obj_id` ASC) VISIBLE,
  CONSTRAINT `objrefs_fk_learningobjs`
    FOREIGN KEY (`obj_id`)
    REFERENCES `test_train_db`.`learning_objectives` (`obj_id`),
  CONSTRAINT `objrefs_fk_topicrefs`
    FOREIGN KEY (`topic_reference_id`)
    REFERENCES `test_train_db`.`topic_references` (`topic_reference_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`questions` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `obj_id` INT NOT NULL,
  `question_text` TEXT NOT NULL,
  `question_answer` TEXT NULL DEFAULT NULL,
  `question_type` VARCHAR(45) NOT NULL,
  `question_difficulty` INT NOT NULL,
  `answer_explaination` VARCHAR(255) NULL DEFAULT NULL,
  `points_definition` VARCHAR(255) NULL DEFAULT NULL,
  `max_points` INT NOT NULL,
  `source/other` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`question_id`, `obj_id`),
  INDEX `questions_fk_learningobjs_idx` (`obj_id` ASC) VISIBLE,
  CONSTRAINT `questions_fk_learningobjs`
    FOREIGN KEY (`obj_id`)
    REFERENCES `test_train_db`.`learning_objectives` (`obj_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`tests` (
  `test_id` INT NOT NULL AUTO_INCREMENT,
  `test_name` VARCHAR(100) NOT NULL,
  `test_description` VARCHAR(255) NOT NULL,
  `created_by` VARCHAR(100) NOT NULL,
  `creation_date` TIMESTAMP(6) NOT NULL,
  `modified_by` VARCHAR(100) NOT NULL,
  `last_modified_date` TIMESTAMP(6) NOT NULL,
  `active_status` TINYINT(1) NOT NULL,
  `training_level` VARCHAR(45) NOT NULL,
  `subject_id` INT NOT NULL,
  `topic_id` INT NOT NULL,
  `total_score` INT NOT NULL,
  PRIMARY KEY (`test_id`),
  UNIQUE INDEX `test_name_UNIQUE` (`test_name` ASC) VISIBLE,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  INDEX `topic_id_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `test_train_db`.`subjects` (`subject_id`),
  CONSTRAINT `topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `test_train_db`.`topics` (`topic_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`test_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`test_questions` (
  `test_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `question_order` INT NOT NULL,
  PRIMARY KEY (`test_id`, `question_id`),
  INDEX `question_id_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `test_train_db`.`questions` (`question_id`),
  CONSTRAINT `testquestions_fk_tests`
    FOREIGN KEY (`test_id`)
    REFERENCES `test_train_db`.`tests` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`testee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`testee` (
  `tester_id` INT NOT NULL AUTO_INCREMENT,
  `testee_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tester_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`test_scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`test_scores` (
  `score_id` INT NOT NULL AUTO_INCREMENT,
  `test_id` INT NOT NULL,
  `tester_id` INT NOT NULL,
  `attempt_date` TIMESTAMP(6) NOT NULL,
  `total_score` INT NOT NULL,
  `pass_status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`score_id`, `tester_id`, `test_id`),
  INDEX `test_id_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `tester_id`
    FOREIGN KEY (`tester_id`)
    REFERENCES `test_train_db`.`testee` (`tester_id`),
  CONSTRAINT `testscores_fk_tests`
    FOREIGN KEY (`test_id`)
    REFERENCES `test_train_db`.`tests` (`test_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_train_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_train_db`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL,
  `is_verified` TINYINT(1) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
